model:
  lambda_depth: 10.
data:
  dataset_name: images
  path: others
training:
  out_dir:  others
  n_workers: 8
  n_training_points: 768
  model_selection_metric: loss_depth_eval
generation:
  generation_dir: generation
  mesh_extension: 'glb'
test:
  model_file: combined.pt